export CONFERIA_DATABASE_HOST=${MYSQL_PORT_3306_TCP_ADDR}
export CONFERIA_DATABASE_PORT=${MYSQL_PORT_3306_TCP_PORT}
export CONFERIA_DATABASE_NAME=${MYSQL_ENV_MYSQL_DATABASE}
export CONFERIA_DATABASE_USER=${MYSQL_ENV_MYSQL_USER}
export CONFERIA_DATABASE_PASSWORD=${MYSQL_ENV_MYSQL_PASSWORD}
